### ISSUE TITLE
Only stereo?

### ISSUE THREAD

**Issue by motoleon** [VisualCodeBase/CodeBase#3]
I work on 7.1 (8 channel) audio, and i have an jesusonic code that works well. I tryed to compile vst with your program, but it show errors like:Compiling DLL file... "MegaBaby" ...
MegaBaby.cpp: In member function 'VstInt32 pvf_EffectClass::pvf_ProcessAudio(float**, VstInt32, VstInt32)':
MegaBaby.cpp:1652:11: error: 'spl4' was not declared in this scope
  spll0_v_=spl4;
           ^~~~
MegaBaby.cpp:1652:11: note: suggested alternative: 's_lh'
  spll0_v_=spl4;
           ^~~~
           s_lh
MegaBaby.cpp:1653:11: error: 'spl5' was not declared in this scope
  spll1_v_=spl5;
           ^~~~
MegaBaby.cpp:1653:11: note: suggested alternative: 's_lh'
  spll1_v_=spl5;
           ^~~~
           s_lh
MegaBaby.cpp:1664:11: error: 'sign' was not declared in this scope
   s0_v_ = sign(spll0_v_);
           ^~~~
MegaBaby.cpp:1664:11: note: suggested alternative: 'sin'
   s0_v_ = sign(spll0_v_);
           ^~~~
           sin
MegaBaby.cpp:1911:41: error: 'spl2' was not declared in this scope
  pvf_SampleOutL=-2.0*pvf_SampleOutL+0.5*spl2+0.5*spl3+salidaL_v_+spl6;
                                         ^~~~
MegaBaby.cpp:1911:41: note: suggested alternative: 's_lh'
  pvf_SampleOutL=-2.0*pvf_SampleOutL+0.5*spl2+0.5*spl3+salidaL_v_+spl6;
                                         ^~~~
                                         s_lh
MegaBaby.cpp:1911:50: error: 'spl3' was not declared in this scope
  pvf_SampleOutL=-2.0*pvf_SampleOutL+0.5*spl2+0.5*spl3+salidaL_v_+spl6;
                                                  ^~~~
MegaBaby.cpp:1911:50: note: suggested alternative: 's_lh'
  pvf_SampleOutL=-2.0*pvf_SampleOutL+0.5*spl2+0.5*spl3+salidaL_v_+spl6;
                                                  ^~~~
                                                  s_lh
MegaBaby.cpp:1911:66: error: 'spl6' was not declared in this scope
  pvf_SampleOutL=-2.0*pvf_SampleOutL+0.5*spl2+0.5*spl3+salidaL_v_+spl6;
                                                                  ^~~~
MegaBaby.cpp:1911:66: note: suggested alternative: 's_lh'
  pvf_SampleOutL=-2.0*pvf_SampleOutL+0.5*spl2+0.5*spl3+salidaL_v_+spl6;
                                                                  ^~~~
                                                                  s_lh
MegaBaby.cpp:1912:66: error: 'spl7' was not declared in this scope
  pvf_SampleOutR=-2.0*pvf_SampleOutR+0.5*spl2+0.5*spl3+salidaR_v_+spl7;
                                                                  ^~~~
MegaBaby.cpp:1912:66: note: suggested alternative: 's_lh'
  pvf_SampleOutR=-2.0*pvf_SampleOutR+0.5*spl2+0.5*spl3+salidaR_v_+spl7;
                                                                  ^~~~
                                                                  s_lh

***** Error *****

Only stereo, two channles?

**Comment by VisualCodeBase** [comment]
no it should support exactly the same as reaper (and more).
this area never tested though. it may be something with channel options.
can you please send a small source test ?
thanks for your reply.

**Comment by micsthepick** [comment]
> can you please send a small source test ?

Here is one with 8 input channels and 2 output channels:

(renamed extension from 7z to gz so that I could upload, should still be able to be opened - at least by 7z)
[multichannelexamplePVF.gz](https://github.com/VisualCodeBase/CodeBase/files/6910605/multichannelexamplePVF.gz)

**Comment by micsthepick** [comment]
don't forget that `spl(channel)` will access the sample with a given `channel` index too.

**Comment by VisualCodeBase** [comment]
yes thank you. in the previous reply i forgot that the new fixed comming soon version will probably solve your issue.
because we already sort, changed and improved  the audio code included spl with variable index.
thanks again

**Comment by motoleon** [comment]
Ok, many thanks
